name: Sign and Release

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:
    inputs:
      tag:
        description: 'SemVer tag to sign (e.g. v1.0.0-alpha.1)'
        required: true

jobs:
  sign-and-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Import signing key
        uses: crazy-max/ghaction-import-gpg@v6
        with:
          gpg_private_key: ${{ secrets.GPG_PRIVATE_KEY }}
          passphrase: ${{ secrets.GPG_PASSPHRASE }}
          git_user_signingkey: true
          git_commit_gpgsign: true
      - name: Verify tag signature
        run: |
          if [[ "${GITHUB_REF}" == refs/tags/* ]]; then
            git verify-tag "${GITHUB_REF_NAME}"
          else
            git tag -s "${{ github.event.inputs.tag }}" -m "Signed release"
          fi
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Build package
        run: |
          python -m pip install --upgrade pip
          pip install build twine
          python -m build
          twine check dist/*
      - name: Publish release
        uses: softprops/action-gh-release@v2
        with:
          files: dist/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
